language: go
go:
- 1.x
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Alan Bradley"
  - GIT_EMAIL="alan@gangleri.net"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
  - TARGET_BRANCH="master"

install: go get -v github.com/spf13/hugo
script:
- hugo

after_success:
  - echo "gangleri.io" > ./public/CNAME
  - ./scripts/deploy.sh

notifications:
  email:
    on_failure: always

before_install:
  - openssl aes-256-cbc -K $encrypted_204d0f6d410b_key -iv $encrypted_204d0f6d410b_iv
    -in travis_key.enc -out travis_key -d
