baseURL = "https://gangleri.io"
languageCode = "en-gb"
title = "Gangleri"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = ""
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "minimalist"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
themesDir = "./themes"

[params]
    site_author = "Alan Bradley"
    site_description = "The blog of Alan Bradley."
    location = "Dublin"
    # Link custom assets relative to /static
    avatar = "img/me.png"
    header_background = "img/desk.jpg"
    header_title = "Gangleri"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "gangleri_"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "gangleri"
    gplus     = ""
